#!/usr/bin/env sh
if git diff --cached --name-only | /usr/bin/grep -Eq "^frontend/.*\.(tsx?|css)$"; then
  echo "Frontend changes detected, rebuilding..."
  cd frontend && bun run build:release && cd ..
  git add dist/
  echo "Done."
fi
